name: LLM Fine-Tuning CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"  # speeds up installs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prefect huggingface_hub

    - name: Run Prefect pipeline
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python src/pipeline.py

    - name: Upload trained model to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python - <<'EOF'
        from huggingface_hub import HfApi
        import os
        api = HfApi()
        api.upload_folder(
            folder_path="llama-ev-lora",
            repo_id="Basel-Amr/llama-ev-lora",
            token=os.getenv("HF_TOKEN"),
            commit_message="Automated model upload via CI/CD"
        )
        EOF

    - name: Job summary
      run: |
        echo "### CI/CD Pipeline Complete 🚀" >> $GITHUB_STEP_SUMMARY
        echo "- Training completed and model uploaded to Hugging Face" >> $GITHUB_STEP_SUMMARY
